version: '3.8'
services:
  primary-backend:
    build: ./primary-backend
    ports:
      - "3000:3000"  # Maps port 3000 of the container to port 3000 on the host
    environment:
      DATABASE_URL: postgresql://postgres:harsh@postgres:5432/postgres

  worker:
    build: ./worker
    ports:
      - "3004:3004"  # Maps port 3000 of the container to port 3000 on the host
    depends_on:
      - primary-backend

  processor:
    build: ./processor
    ports:
      - "3003:3003"
    depends_on:
      - primary-backend

  hooks:
    build: ./hooks
    ports:
      - "3002:3002"  # Maps port 3002 of the container to port 3002 on the host
    depends_on:
      - primary-backend

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harsh
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Maps port 5432 of the container to port 5432 on the host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persists data across container restarts

volumes:
  postgres-data:  # Defines a volume for storing the database data
