version: '3.8'
services:
  primary-backend:
    build: ./primary-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:harsh@postgres:5432/postgres

  worker:
    build: ./worker
    ports:
      - "3004:3004"
    environment:
      DATABASE_URL: postgresql://postgres:harsh@postgres:5432/postgres  
    depends_on:
      - primary-backend
      - kafka

  processor:
    build: ./processor
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://postgres:harsh@postgres:5432/postgres  
    depends_on:
      - primary-backend
      - kafka

  hooks:
    build: ./hooks
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:harsh@postgres:5432/postgres  
    depends_on:
      - primary-backend
      - kafka

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harsh
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://54.173.126.56:9092,PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_LOG_DIRS: /mnt/kafka-logs   # Location on the mounted EBS volume for Kafka logs
    volumes:
      - /mnt/kafka-logs:/mnt/kafka-logs # Mount the EBS volume
    depends_on:
      - zookeeper

volumes:
  postgres-data:
